apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: valkey
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-wave-health: all
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://valkey.io/valkey-helm/
      chart: valkey
      targetRevision: 0.11.0
      helm:
        valueFiles:
          - $values/infrastructure/valkey/values.yaml
    - repoURL: https://github.com/freecloudinitiative/nonprod-k3s-manifests.git
      targetRevision: main
      path: infrastructure/valkey
      ref: values
      directory:
        include: certificate.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: valkey
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
