apiVersion: v1
kind: Namespace
metadata:
  name: backend
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    name: backend
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
