apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secrets
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  target:
    name: grafana-secrets
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: grafana
        property: admin-user
        metadataPolicy: None
    - secretKey: admin-password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: grafana
        property: admin-password
        metadataPolicy: None
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: authentik
        property: grafana-oidc-secret
        metadataPolicy: None
