apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: valkey-auth
  namespace: valkey
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-store
  target:
    name: valkey-auth
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: default
      remoteRef:
        key: valkey
        property: password
