apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-store
  target:
    name: argocd-oidc-secret
    creationPolicy: Owner
  data:
    - secretKey: clientSecret
      remoteRef:
        key: authentik
        property: argocd-oidc-secret
