apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-wave-health: all
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.goauthentik.io
      chart: authentik
      targetRevision: 2026.8.0
      helm:
        valueFiles:
          - $values/infrastructure/authentik/values.yaml
    - repoURL: https://github.com/freecloudinitiative/nonprod-k3s-manifests.git
      targetRevision: main
      path: infrastructure/authentik
      ref: values
      directory:
        include: '{blueprint.yaml,certificate.yaml,footer-links-job.yaml,networkpolicy.yaml,service-account.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
