apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns-nonprod-hosts
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-wave-health: all
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/freecloudinitiative/nonprod-k3s-manifests.git
    targetRevision: main
    path: infrastructure/coredns
    directory:
      include: configmap.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
