apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-configs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-wave-health: all
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/freecloudinitiative/nonprod-k3s-manifests.git
    targetRevision: main
    path: infrastructure/cert-manager
    directory:
      include: '{cluster-issuer-*.yaml,certificate-*.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - CreateNamespace=true
