apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-wave-health: all
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.21.1
      helm:
        valueFiles:
          - $values/infrastructure/cert-manager/values.yaml
    - repoURL: https://github.com/freecloudinitiative/nonprod-k3s-manifests.git
      targetRevision: main
      path: infrastructure/cert-manager
      ref: values
      directory:
        include: service.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - CreateNamespace=true
