apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collector
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-wave-health: all
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-collector
      targetRevision: 0.169.0
      helm:
        valueFiles:
          - $values/infrastructure/opentelemetry/values.yaml
    - repoURL: https://github.com/freecloudinitiative/nonprod-k3s-manifests.git
      targetRevision: main
      path: infrastructure/opentelemetry
      ref: values
      directory:
        include: service.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - CreateNamespace=true
