apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "compute-service.fullname" . }}-pullsecret-reader
  namespace: {{ .Values.instancePullSecret.sourceNamespace | quote }}
  labels:
    {{- include "compute-service.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: [{{ .Values.instancePullSecret.sourceName | quote }}]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "compute-service.fullname" . }}-pullsecret-reader
  namespace: {{ .Values.instancePullSecret.sourceNamespace | quote }}
  labels:
    {{- include "compute-service.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "compute-service.fullname" . }}-pullsecret-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "compute-service.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
